apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-pass
type: Opaque
data:
  password: dW5pcg==
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: unirregistry.azurecr.io/mariadb:11.3.2
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: unirpassword
        - name: MARIADB_DATABASE
          value: webapp
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "managed"
        resources:
          requests:
            storage: 10Gi
