apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: webapp
  selector:
    app: webapp
  type: LoadBalancer